dao:
  gemeentes:
    security-method: private_key_jwt
    config:
      leuven:
        naam: Leuven
        kbonummer: '0207521503'
        clientid: 88dee742-46c5-4e81-992c-983ec02d55d0
        clientsecret: '{ "kid": "dbb977e3-9b4b-4249-9d24-3833aeafbea7", "kty": "EC", "crv": "P-521", "x": "AP452XSt1hOl79FsrfNYjMACVN-Dku6gc6n6xkC-2xOYsEWMWo7e9QtqDTs7r0Lx3bwEUO715_Ys9QhD8iiELmhB", "y": "AS4RtrC6AySeBlZFy9CRljzKJLuUhueFIKNwbu-AyD1utg_2IUvyRb0EmBK1P4VJQZbzrttTRlCyzePilZ3edOQo", "d": "AJgHcXAh7qKrIQO3bs6UMqXV-sSBwLqluM8qtcmiJqp70zuqbPUcwcuuNsaMjtSGKLOIIaqfUG93BB0hIMAiccQl", "use": "sig", "alg": "ES512"}'
      oostende:
        naam: Oostende
        kbonummer: '0207436775'
        clientid: cb694f67-e111-401d-bf22-61f9b7698beb
        clientsecret: '{ "kid": "dbb977e3-9b4b-4249-9d24-3833aeafbea7", "kty": "EC", "crv": "P-521", "x": "AP452XSt1hOl79FsrfNYjMACVN-Dku6gc6n6xkC-2xOYsEWMWo7e9QtqDTs7r0Lx3bwEUO715_Ys9QhD8iiELmhB", "y": "AS4RtrC6AySeBlZFy9CRljzKJLuUhueFIKNwbu-AyD1utg_2IUvyRb0EmBK1P4VJQZbzrttTRlCyzePilZ3edOQo", "d": "AJgHcXAh7qKrIQO3bs6UMqXV-sSBwLqluM8qtcmiJqp70zuqbPUcwcuuNsaMjtSGKLOIIaqfUG93BB0hIMAiccQl", "use": "sig", "alg": "ES512"}'